/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { TrackingActivity } from '../types';
import { getPremiumCartoonAvatar } from './avatar-utils';

export const MOCK_ACTIVITIES: TrackingActivity[] = [
  {
    id: 'act_1',
    user_id: 'user_kelvin',
    athlete_name: 'Kelvin Rudyanto',
    athlete_avatar: getPremiumCartoonAvatar('Kelvin Rudyanto', 'male'),
    sport_id: 'sport_badminton',
    sport_name: 'Badminton',
    sport_icon: 'Sparkles',
    title: 'High-Intensity Singles Sparring at GOR C-Tra Arena',
    duration: '01:25:00',
    duration_minutes: 85,
    calories: 620,
    heart_rate: 164,
    intensity: 'High-intensity',
    is_personal_record: true,
    xp_earned: 250,
    reputation_gained: 15,
    location: 'GOR C-Tra Arena, Bandung',
    date: '2026-06-27T08:30:00Z',
    achievement_badge: 'Consistent Trainer',
    respect_count: 24,
    comment_count: 5,
    has_respected: true,
    has_saved: false,
    notes: 'Incredible speed on court. Jump smashes felt explosive. Smashes clocked at 375 km/h. Need to work on backhand net recovery.'
  },
  {
    id: 'act_2',
    user_id: 'user_arya',
    athlete_name: 'Arya Wibowo',
    athlete_avatar: getPremiumCartoonAvatar('Arya Wibowo', 'male'),
    sport_id: 'sport_running',
    sport_name: 'Running',
    sport_icon: 'Zap',
    title: 'Morning Tempo Run - Jatinangor Ring Road',
    distance: '8.4 km',
    duration: '00:39:12',
    duration_minutes: 39,
    calories: 540,
    pace: '4:40 /km',
    elevation_gain: '64m',
    heart_rate: 152,
    intensity: 'Tempo',
    is_personal_record: false,
    xp_earned: 180,
    reputation_gained: 8,
    location: 'Jatinangor Ring Road, Sumedang',
    date: '2026-06-27T06:15:00Z',
    achievement_badge: 'Early Grinder',
    respect_count: 18,
    comment_count: 2,
    has_respected: false,
    has_saved: true,
    notes: 'Cool breeze, legs felt light today. Pushed harder in the final 2 kilometers.'
  },
  {
    id: 'act_3',
    user_id: 'user_nadia',
    athlete_name: 'Nadia Syafira',
    athlete_avatar: getPremiumCartoonAvatar('Nadia Syafira', 'female'),
    sport_id: 'sport_tennis',
    sport_name: 'Tennis',
    sport_icon: 'Target',
    title: 'Clay Court Drilling Session in South Jakarta',
    duration: '02:00:00',
    duration_minutes: 120,
    calories: 780,
    heart_rate: 148,
    intensity: 'Moderate',
    is_personal_record: false,
    xp_earned: 300,
    reputation_gained: 12,
    location: 'Elite Tennis Club, South Jakarta',
    date: '2026-06-26T16:00:00Z',
    respect_count: 32,
    comment_count: 6,
    has_respected: false,
    has_saved: false,
    notes: 'Heavy spin baseline rallies. Serves were highly accurate. Ready for the upcoming Priangan clay court open!'
  },
  {
    id: 'act_4',
    user_id: 'user_farhan',
    athlete_name: 'Farhan Maulana',
    athlete_avatar: getPremiumCartoonAvatar('Farhan Maulana', 'male'),
    sport_id: 'sport_futsal',
    sport_name: 'Futsal',
    sport_icon: 'Activity',
    title: 'Weekend League Match Day - Futsal Town',
    duration: '01:00:00',
    duration_minutes: 60,
    calories: 680,
    heart_rate: 172,
    intensity: 'Extreme',
    is_personal_record: true,
    xp_earned: 400,
    reputation_gained: 25,
    location: 'Futsal Town, Bandung',
    date: '2026-06-25T20:00:00Z',
    achievement_badge: 'Match Winner',
    respect_count: 45,
    comment_count: 11,
    has_respected: true,
    has_saved: true,
    notes: 'Won the championship match 5-3! Scored a hat-trick today. Legs are absolutely spent but feeling ecstatic.'
  },
  {
    id: 'act_5',
    user_id: 'user_kelvin',
    athlete_name: 'Kelvin Rudyanto',
    athlete_avatar: getPremiumCartoonAvatar('Kelvin Rudyanto', 'male'),
    sport_id: 'sport_running',
    sport_name: 'Running',
    sport_icon: 'Zap',
    title: 'Late Night Cardio Blast - Gasibu Loop',
    distance: '5.0 km',
    duration: '00:22:45',
    duration_minutes: 23,
    calories: 390,
    pace: '4:33 /km',
    elevation_gain: '12m',
    heart_rate: 168,
    intensity: 'Tempo',
    is_personal_record: true,
    xp_earned: 150,
    reputation_gained: 10,
    location: 'Gasibu Sports Field, Bandung',
    date: '2026-06-24T21:00:00Z',
    achievement_badge: 'Pace Breaker',
    respect_count: 19,
    comment_count: 4,
    has_respected: false,
    has_saved: false,
    notes: 'Pushed for a sub-23 mins target on the 5K loop. Smashed the personal record. Heart was pounding!'
  },
  {
    id: 'act_6',
    user_id: 'user_budi',
    athlete_name: 'Budi Santoso',
    athlete_avatar: getPremiumCartoonAvatar('Budi Santoso', 'male'),
    sport_id: 'sport_basketball',
    sport_name: 'Basketball',
    sport_icon: 'Dribbble',
    title: 'Halfcourt Pickup Wars under the Lights',
    duration: '01:40:00',
    duration_minutes: 100,
    calories: 720,
    heart_rate: 158,
    intensity: 'High-intensity',
    is_personal_record: false,
    xp_earned: 220,
    reputation_gained: 12,
    location: 'Taman Menteng Basketball Court, Jakarta',
    date: '2026-06-23T19:30:00Z',
    respect_count: 27,
    comment_count: 8,
    has_respected: true,
    has_saved: false,
    notes: 'Played 5 consecutive 3x3 games. Shooting streak was hot (70% field goal rate). Solid competitive runs.'
  }
];
